### PR TITLE
Update the SKU autocomplete with new required info

### PR DESCRIPTION
**Pull request by Gidgidonihah**

### CODE REVIEW

**Comment by Gidgidonihah** [comment]
@jtprince once this is released, go ahead and assign it to @baileymatthewr and have him validate the changes and make any additional changes that are needed.

**Comment by jtprince** [comment]
@baileymatthewr - can you validate that this is what is actually happening.  I have this assigned to you until you sign off on it (that the changes in the api match the actual behavior).  Then I will approve it.  Thanks!!!

**Comment by baileymatthewr** [comment]
@jtprince : I have reviewed and made my corrections. I would like to make sure this is good to go at this point.

**Comment by baileymatthewr** [comment]
@jtprince : One last thing is that I had to change 'type' to 'method'. That was the only change.

**Comment by baileymatthewr** [comment]
@Gidgidonihah : Can you merge and release this, please?

**Pull request merged**
